name: testing

on: [push]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- name: Install deps
      #  run: pip install -r requirements.txt
      - name: Run CI/CD Tests
        run: echo "This is the test run!"
