name: testing

on: [push]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
      - uses: actions/checkout@v4

      - name: Run CI/CD Tests
      # run: echo "This is the test run!"
        run: python -m test_directory
